### ISSUE TITLE
Dictionary name pluralization on FixedStringsAndDictionary enum generation mode

### ISSUE THREAD

**Issue by gangstatracer** [skbkontur/TypeScript.ContractGenerator#4]
Constant dictionary providing quick access to enum values now named by simple type concatenation with 's':
https://github.com/skbkontur/TypeScript.ContractGenerator/blob/89ee35694981db76f95b9e207cca352ad760ffce/TypeScript.ContractGenerator/TypeBuilders/FixedStringsAndDictionaryTypeBuildingContext.cs#L33
Name should be generated by some "true" pluralization.

**Comment by fakefeik** [comment]
True pluralization is hard and I'm not sure it's needed. It would be good to add some examples to this issue.  What if enum is already a plural? How would you pluralize enum named `DocumentTypes`?

**Comment by gangstatracer** [comment]
Pluralization can be accomplished by https://github.com/Humanizr/Humanizer#pluralize.
Fow plural words we could use some suffix ('Values', for examle).

**Comment by fakefeik** [comment]
OTOH, if we used 'Values' suffix instead of 's' for any enum, we would not need to add some third-party library to our package, we also would not need to allow this library configuration through our code (which we would need to do in order to allow users to add unknown plurals).

**Comment by gangstatracer** [comment]
What about `Pluralization` option? Something like:
```csharp
public class FlowTypeGenerationOptions
{
    ...
    public Func<string, string> EnumPluralize { get; set; } = s => $"{s}Values";
    ...
}
```

**Comment by fakefeik** [comment]
this looks better, this way, new package reference and library configuration will be in user code
