### ISSUE TITLE
Improve readme for setting output file location

### ISSUE THREAD

**Issue by manuel3108** [skbkontur/TypeScript.ContractGenerator#58]
This looks like the code you need to generate this, but the documentation barely touches that. I would suggest improving the doc maybe with a short example.

```cs
public class TypescriptTypeGenerator : ICustomTypeGenerator
{
    public string GetTypeLocation(ITypeInfo type)
    {
        return "myfilename"; // without extension! .ts will be added automatically.
    }

    public TypeScriptTypeMemberDeclaration? ResolveProperty(TypeScriptUnit unit, ITypeGenerator typeGenerator, ITypeInfo type, IPropertyInfo property)
    {
        return null;
    }

    public ITypeBuildingContext? ResolveType(string initialUnitPath, ITypeGenerator typeGenerator, ITypeInfo type, ITypeScriptUnitFactory unitFactory)
    {
        return null;
    }
}
```

**Comment by manuel3108** [comment]
Also I think it would be good to add, that you can insert multiple types for the `RootTypesProvider`.

Additionaly we have the possibility to find required types with reflection (but that's propably something everyone can figure out on their own)

```cs
var types = AppDomain.CurrentDomain.GetAssemblies()
                       .SelectMany(t => t.GetTypes())
                       .Where(t => t.IsClass && t.Namespace is not null && t.Namespace.Contains(ProgramDefaults.SharedTypesNamespace))
                       .ToArray();

var generator = new TypeScriptGenerator(TypeScriptGenerationOptions.Default, new TypescriptTypeGenerator(), new RootTypesProvider(types));

/// ....
```

**Comment by fakefeik** [comment]
Project documentation definitely needs improvement, will get to it in the near future

thank you for the feedback

**Comment by manuel3108** [comment]
Sounds great!
I will keep adding things here, if i find morre things.

One thing today i.e.

If you have an enum in your shared types, it will always generate a string typescript enum like this:
```ts
export enum MessageType {
    SAVE_CONFIGURATION_REQUEST = 'SAVE_CONFIGURATION_REQUEST',
    CONFIGURATION_REQUEST = 'CONFIGURATION_REQUEST',
    CONFIGURATION_RESPONSE = 'CONFIGURATION_RESPONSE',
    CONFIGURATION_VALIDATION_REQUEST = 'CONFIGURATION_VALIDATION_REQUEST',
    CONFIGURATION_VALIDATION_RESPONSE = 'CONFIGURATION_VALIDATION_RESPONSE',
}
```

although it looks like this in c#
```cs
public enum MessageType
{
    SAVE_CONFIGURATION_REQUEST = 1,
    CONFIGURATION_REQUEST = 2,
    CONFIGURATION_RESPONSE = 3,
    CONFIGURATION_VALIDATION_REQUEST = 4,
    CONFIGURATION_VALIDATION_RESPONSE = 5,
}
```

In order to be able to correctly read back the messages send from c# to ts/js, you will need to add something like this to the message sending process in c#:
```cs
_serializationSettings = new JsonSerializerSettings();
_serializationSettings.ContractResolver = new CamelCasePropertyNamesContractResolver(); // important line

var data = JsonConvert.SerializeObject(messageResponse, _serializationSettings);
```

**Comment by fakefeik** [comment]
Enums as strings is more commonly used to pass objects from frontend to backend and vice versa

If you really want enums as integers, you could make custom EnumTypeBuildingContext based on [TypeScriptEnumTypeBuildingContext](https://github.com/skbkontur/TypeScript.ContractGenerator/blob/eea8b6ec8ab1ae0ecd24521322288de570fc576f/TypeScript.ContractGenerator/TypeBuilders/TypeScriptEnumTypeBuildingContext.cs) and pass it to your CustomTypeGenerator:
```
public class ExampleCustomGenerator : CustomTypeGenerator
{
  public ExampleCustomGenerator()
  {
    WithTypeBuildingContext(t => t.IsEnum, (unit, type) => new TypeScriptEnumTypeBuildingContext(unit, type));
  }
}
```

As for camelCase property names, it is also used a lot more commonly than PascalCase, but I suppose it's a good point of extension, user should have the ability to change property names when generating TypeScript types

**Comment by manuel3108** [comment]
Thanks for your answer. But I think you understood my comment wrong. 

I fully agree the decision that have been made and think that they are right and important.

I just wanted to outline which steps need to be taken, to make Newton soft.JSON and JSON.parse work flawlessly together.

And these were just the two hickups I encountered over the last few days

**Comment by fakefeik** [comment]
Added detailed [Quick Start guide](https://github.com/skbkontur/TypeScript.ContractGenerator/wiki/Quick-Start) and updated [example](https://github.com/skbkontur/TypeScript.ContractGenerator/tree/master/AspNetCoreExample.Api), hope that helps
