### ISSUE TITLE
enums

### ISSUE THREAD

**Issue by obecny** [skbkontur/TypeScript.ContractGenerator#74]
this is C# enum
```
public enum Foo
{
    Left,
    Right,
    None,
}
```

this was generated
```
export enum Foo {
    Left = 'Left',
    Right = 'Right',
    None = 'None',
}

```

but then I have a json object being sent from "frontend" to backend which looks like

```
const foo: FooObject = {
  direction: Foo.Left
};
```

on c# side
```
JsonSerializerOptions JsonOptions = new JsonSerializerOptions
        { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
...

JsonSerializer.Deserialize<FooObject>("{\"direction\":\"Left\"}", JsonOptions);
```

and I got error
the only way to fix it is to change json to
```
JsonSerializer.Deserialize<FooObject>("{\"direction\":0}", JsonOptions);
```
So is there a way to generate an enum for typescript which should look like
```
export enum Foo {
    Left,
    Right,
    None,
}
```

thank you

**Comment by fakefeik** [comment]
you can either use JsonStringEnumConverter on backend to always pass enum values as strings or build your own custom enum type builder based on [TypeScriptEnumTypeBuildingContext](https://github.com/skbkontur/TypeScript.ContractGenerator/blob/master/TypeScript.ContractGenerator/TypeBuilders/TypeScriptEnumTypeBuildingContext.cs) and use it in your `CustomGenerator`

**Comment by obecny** [comment]
@fakefeik thx a lot
